[package]
name = "gamezap-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.19"
pollster = "0.3.0"
raw-window-handle = "0.5.2"
sdl2 = {git = "https://github.com/Rust-SDL2/rust-sdl2.git", features = ["raw-window-handle"]}
wgpu = "0.17.0"
anyhow = "1.0.72"
nalgebra = "0.32.3"
tobj = { version = "4.0.0", features = ["async"] }
cfg-if = "1.0.0"
time = "0.3.24"

[dependencies.image]
version = "0.24.6"
default-features = false
features = ["png", "jpeg"]
